stages:
  - build
  - test
  - deploy

default:
  image: node:22
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - npm ci

build-job:
  stage: build
  script:
    - npm run build

test-job:
  stage: test
  script:
    - npm run lint

deploy-job:
  stage: deploy
  script:
    - npm run deploy
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
    - when: never